CREATE TABLE RECIPES(
R_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
RECIPE_NAME TEXT,
RECIPE_REQUIREMENT TEXT,
RECIPE_PROCESS TEXT
);

CREATE TABLE RECIPES_INGREDIENTS(
  RI_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  INGREDIENT_ID NUMBER,
  R_ID INT,
  CONSTRAINT RECIPES_INGREDIENTSFK FOREIGN KEY (R_ID) REFERENCES RECIPES (R_ID)
);
